title: 莎士比亞 - 吳淡如
description: 莎士比亞 - 吳淡如
time: Mon, 26 Aug 2024 08:16:38 +0000
items:
  - title: 01. 李爾王之一
    size: 12896789
    duration: 537
  - title: 02. 李爾王之二
    size: 15094049
    duration: 628
  - title: 03. 李爾王之三
    size: 14266477
    duration: 594
  - title: 04. 李爾王之四
    size: 15746967
    duration: 656
  - title: 05. 哈姆雷特之一
    size: 13184123
    duration: 549
  - title: 06. 哈姆雷特之二
    size: 13177863
    duration: 549
  - title: 07. 哈姆雷特之三
    size: 13075825
    duration: 544
  - title: 08. 哈姆雷特之四
    size: 13832659
    duration: 576
  - title: 09. 馬克白之一
    size: 12976291
    duration: 540
  - title: 10. 馬克白之二
    size: 12337771
    duration: 514
  - title: 11. 馬克白之三
    size: 12900545
    duration: 537
  - title: 12. 馬克白之四
    size: 13485855
    duration: 561
  - title: 13. 奧賽羅之一
    size: 17477857
    duration: 728
  - title: 14. 奧賽羅之二
    size: 14587615
    duration: 607
  - title: 15. 奧賽羅之三
    size: 20537119
    duration: 855
  - title: 16. 羅密歐與茱麗葉之一
    size: 13622323
    duration: 567
  - title: 17. 羅密歐與茱麗葉之二
    size: 13589145
    duration: 566
  - title: 18. 羅密歐與茱麗葉之三
    size: 13405727
    duration: 558
  - title: 19. 羅密歐與茱麗葉之四
    size: 11947773
    duration: 497
  - title: 20. 羅密歐與茱麗葉之五
    size: 9609037
    duration: 400
  - title: 21. 暴風雨之一
    size: 12520100
    duration: 782
  - title: 22. 暴風雨之二
    size: 18465844
    duration: 1153
  - title: 23. 仲夏夜之夢之一
    size: 13987168
    duration: 874
  - title: 24. 仲夏夜之夢之二
    size: 14014048
    duration: 875
  - title: 25. 仲夏夜之夢之三
    size: 8424160
    duration: 526
  - title: 26. 威尼斯商人之一
    size: 13466464
    duration: 841
  - title: 27. 威尼斯商人之二
    size: 13033312
    duration: 814
  - title: 28. 威尼斯商人之三
    size: 14936800
    duration: 933
  - title: 29. 冬天的故事之一
    size: 10870238
    duration: 679
  - title: 30. 冬天的故事之二
    size: 11993824
    duration: 749
  - title: 31. 冬天的故事之三
    size: 13359328
    duration: 834
  - title: 32. 馴悍記之一
    size: 11126748
    duration: 695
  - title: 33. 馴悍記之二
    size: 12150492
    duration: 759
  - title: 34. 馴悍記之三
    size: 9645660
    duration: 602
  - title: 35. 一報還一報之一
    size: 11163232
    duration: 697
  - title: 36. 一報還一報之二
    size: 15378784
    duration: 961
  - title: 37. 一報還一報之三
    size: 11375584
    duration: 710
  - title: 38. 第十二夜之一
    size: 11438174
    duration: 714
  - title: 39. 第十二夜之二
    size: 12895838
    duration: 805
  - title: 40. 第十二夜之三
    size: 15860318
    duration: 991
